PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dba: <http://dbpedia.org/page/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex:  <http://ex.org/a#>

CONSTRUCT {
  ?URI a dbo:movie;
    ex:imdb_rating ?rate;
    ex:num_votes ?votes.
}
WHERE {
  BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?URI).
  BIND (xsd:float(?averageRating) AS ?rate).
  BIND (xsd:integer(?numVotes) AS ?votes).
}
