PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mvo: http://www.movieontology.org/2009/11/09/movieontology.owl

CONSTRUCT {
  ?URI a dbo:movie;
    dbo:title ?primaryTitle;
    mvo:title ?originalTitle;
    a ?titleType;
    mvo:isAdult ?adult;
    mvo:releasedate ?year;
    mvo:runtime ?runtime.
}

WHERE {
  BIND (URI(CONCAT('http://www.imdb.com/title/', ?tconst)) AS ?URI)
  BIND (xsd:integer(?isAdult) AS ?adult)
  BIND (xsd:integer(?startYear) AS ?year)
  BIND (xsd:integer(?runtimeMinutes) AS ?runtime)
}
